version: '3'
services:
  # DB
  postgres:
    platform: linux/x86_64
    image: 'postgres:15-alpine'
    container_name: postgres
    env_file: ./.env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  # API
  api:
    depends_on:
      postgres:
        condition: service_healthy
    image: rest-api
    build:
      context: ./rest-api
      dockerfile: Dockerfile
    env_file: ./.env
    container_name: api
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      - spring.datasource.url=jdbc:postgresql://postgres:5432/$POSTGRES_DB
      - spring.datasource.username=$POSTGRES_USER
      - spring.datasource.password=$POSTGRES_PASSWORD
      - security.jwt.token.expire-length=$JWT_TOKEN_TTL
      - spring.jpa.hibernate.ddl-auto=validate
    healthcheck:
      test: [ "CMD-SHELL", "curl -X GET localhost:8080/success" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # FRONT
  # TODO